# Generated by Django 4.2.8 on 2023-12-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_type_usuario_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/%Y/%m/%d')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Cursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('nit', models.PositiveIntegerField(default=0)),
                ('direccion', models.CharField(max_length=150)),
                ('forma_pago', models.CharField(max_length=100)),
                ('correo_conf', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cursos')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.usuario')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'Asignacion',
                'ordering': ['id'],
            },
        ),
    ]
