# Generated by Django 4.2.8 on 2023-12-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_cursos_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.ImageField(choices=[[0, 'Desbloqueo'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'consulta']], upload_to='')),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
