# Generated by Django 4.2.8 on 2023-12-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Desbloqueo'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'consulta']]),
        ),
    ]
